//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesMarketplace
{
    using System;
    using System.Collections.Generic;
    
    public partial class DownloadedNote
    {
        public int DId { get; set; }
        public int Note { get; set; }
        public int Users { get; set; }
        public int Buyer { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public string NoteTitle { get; set; }
        public string Attachment { get; set; }
        public int SellPrice { get; set; }
        public string Category { get; set; }
        public string BuyerEmail { get; set; }
        public string BuyerMobile { get; set; }
        public Nullable<int> AttachmentSize { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual NoteDetail NoteDetail { get; set; }
    }
}
