//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesMarketplace
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class UserProfileDetail
    {
        public int ID { get; set; }
        public int Users { get; set; }


        public Nullable<System.DateTime> DOB { get; set; }

        public string Gender { get; set; }
        public string PhoneNumber { get; set; }

        [RegularExpression("([0-9][0-9]*)", ErrorMessage = "Only number")]
        public string Number { get; set; }
        public string ProfilePicture { get; set; }


        [RegularExpression(@"([a-zA-Z0-9\s_\\.\-:])+(.png|.jpg|.gif|.PNG|.JPG)$", ErrorMessage = "Only Image files allowed.")]
        public HttpPostedFileBase ProfilePic { get; set; }

        [Required]
        public string Address1 { get; set; }
        [Required]
        public string Address2 { get; set; }
        [Required]
        public string City { get; set; }
        [Required]
        public string States { get; set; }
        [Required]
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "Only number")]
        public string ZipCode { get; set; }
        [Required]
        public string Country { get; set; }

        public string CountryCode { get; set; }

        public string University { get; set; }

        [Required]
        public string College { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }

        public virtual User User { get; set; }
    }
}
